"""updated Student model

Revision ID: 801ff256135e
Revises: e0eda8251209
Create Date: 2024-02-19 14:41:41.270796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801ff256135e'
down_revision = 'e0eda8251209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Fee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('Fee')

    # ### end Alembic commands ###
