"""updated Student model

Revision ID: 8805ff87e163
Revises: 801ff256135e
Create Date: 2024-02-19 14:44:15.801198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8805ff87e163'
down_revision = '801ff256135e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('Dob')
        batch_op.drop_index('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('Name', ['Name'], unique=True)
        batch_op.create_index('Dob', ['Dob'], unique=True)

    # ### end Alembic commands ###
